void GeraPesos(TipoPesos p);
TipoIndice h(TipoChave Chave, TipoPesos p);
void Inicializa(TipoDicionario T);
TipoApontador Pesquisa(TipoChave Ch, TipoPesos p, TipoDicionario T);
void Insere(TipoItem * x, TipoPesos p, TipoDicionario T);
void Retira(TipoChave Ch, TipoPesos p, TipoDicionario T);
void DefineAlfabeto(TipoAlfabeto Alfabeto, FILE *ArqAlf);
void ExtraiProximaPalavra (TipoPalavra Result, int *TipoIndice, char *Linha, FILE *ArqTxt, TipoAlfabeto Alfabeto);
char *Trim(char *str);
void PrimeiraEtapa(FILE *ArqTxt, TipoAlfabeto Alfabeto, int *TipoIndice, TipoPalavra Palavra, char *Linha, TipoDicionario Vocabulario, TipoPesos p);
void CalculaCompCodigo(TipoDicionario A, int n);
void Particao(TipoIndice Esq, TipoIndice Dir, TipoIndice *i, TipoIndice *j, TipoDicionario A);
void Ordena(TipoIndice Esq, TipoIndice Dir, TipoDicionario A);
void QuickSort(TipoDicionario A, TipoIndice *n);
TipoIndice OrdenaPorFrequencia(TipoDicionario Vocabulario);
void GravaNumInt(FILE *ArqComprimido, int Num);
int LeNumInt(FILE *ArqComprimido);
int ConstroiVetores(TipoVetoresBO VetoresBaseOffset, TipoDicionario Vocabulario, int n, FILE *ArqComprimido);
int SegundaEtapa(TipoDicionario Vocabulario, TipoVetoresBO VetoresBaseOffset, TipoPesos p, FILE *ArqComprimido); 
void Escreve(FILE *ArqComprimido, int *Codigo, int *c);
int Codifica(TipoVetoresBO VetoresBaseOffset, int Ordem, int *c, int MaxCompCod);
void TerceiraEtapa(FILE *ArqTxt, TipoAlfabeto Alfabeto, int *TipoIndice, TipoPalavra Palavra, char *Linha, TipoDicionario Vocabulario, TipoPesos p, TipoVetoresBO VetoresBaseOffset, FILE *ArqComprimido, int MaxCompCod);
void Compressao(FILE *ArqTxt, FILE *ArqAlf, FILE *ArqComprimido);
int LeVetores(FILE *ArqComprimido, TipoBaseOffset *VetoresBaseOffset);
int LeVocabulario(FILE *ArqComprimido, TipoVetorPalavra Vocabulario);
void Atribui(TipoPadrao P, int Codigo, int c);
